- op: add
  path: /spec/template/spec/containers/0/resources/limits/cpu
  value: 100m

- op: add
  path: /spec/template/spec/containers/0/resources/limits/memory
  value: 256Mi

- op: add
  path: /spec/template/spec/containers/0/resources/requests/cpu
  value: 50m

- op: add
  path: /spec/template/spec/containers/0/resources/requests/memory
  value: 128Mi