bases:
  - ../../base

patchesJson6902:
- target:
    group: apps
    version: v1
    kind: Deployment
    name: example-app
  path: deployment-patch.yaml
- target:
    group: apps
    version: v1
    kind: HorizontalPodAutoscaler
    name: example-app
  path: hpa-patch.yaml

  images:
  - name: example-app
    newName: example-app
    newTag: prod